import { chromium } from 'playwright';
import { safeFetch, validatePublicUrl } from './security.js';
import { analyzeHtml, computeScores } from './analyzers.js';

async function textCheck(origin,path){try{const r=await safeFetch(new URL(path,origin).href);const text=(await r.text()).slice(0,500000);return{verified:true,status:r.status,present:r.ok,content:text}}catch(e){return{verified:false,present:false,error:e.message}}}
export async function auditSite(input, onProgress=()=>{}) {
  const started=Date.now(); const valid=await validatePublicUrl(input); onProgress(10,'Connexion sécurisée au site');
  const t=Date.now(), response=await safeFetch(valid.href);
  if (response.status >= 400) {
    const challenged = response.status === 403 && (response.headers.get('cf-mitigated') || /cloudflare/i.test(response.headers.get('server') || ''));
    throw new Error(challenged ? 'Le site protège cette page contre les robots. Analyse non vérifiée.' : `La page répond avec une erreur HTTP ${response.status}.`);
  }
  const buf=Buffer.from(await response.arrayBuffer());
  if(buf.length>5_000_000) throw new Error('La page dépasse la taille maximale autorisée (5 Mo).');
  const type=response.headers.get('content-type')||''; if(!type.includes('text/html')) throw new Error('Cette URL ne renvoie pas une page HTML.');
  const html=buf.toString('utf8'), finalUrl=response.url||valid.href;
  const safeHeaderNames=['content-type','content-length','content-encoding','cache-control','content-security-policy','strict-transport-security','x-content-type-options','referrer-policy','permissions-policy','server','x-powered-by'];
  const headers=Object.fromEntries(safeHeaderNames.map(name=>[name,response.headers.get(name)]).filter(([,value])=>value)); onProgress(30,'Analyse SEO et structure');
  const base=analyzeHtml(html,finalUrl,headers,response.status,{ms:Date.now()-t,bytes:buf.length});
  const [robots,sitemap]=await Promise.all([textCheck(finalUrl,'/robots.txt'),textCheck(finalUrl,'/sitemap.xml')]); onProgress(50,'Contrôle robots.txt et sitemap');
  const techIssues=[];
  if(!robots.present) techIssues.push({category:'Technical',level:'improvement',title:'robots.txt absent ou inaccessible',explanation:'Aucun robots.txt exploitable n’a été trouvé.',impact:'Les consignes de crawl ne sont pas centralisées.',recommendation:'Publier un robots.txt valide.',difficulty:'Facile',automatable:true});
  if(!sitemap.present) techIssues.push({category:'Technical',level:'important',title:'sitemap.xml absent ou inaccessible',explanation:'Aucun sitemap XML n’a été trouvé à l’emplacement standard.',impact:'La découverte des pages peut être moins efficace.',recommendation:'Générer et déclarer un sitemap XML.',difficulty:'Facile',automatable:true});
  let browser, shots={desktop:null,mobile:null}, visual={verified:false,notes:[]};
  try { browser=await chromium.launch({headless:true}); const page=await browser.newPage({viewport:{width:1440,height:1000}}); await page.goto(finalUrl,{waitUntil:'networkidle',timeout:25000}); await page.waitForTimeout(600); shots.desktop=(await page.screenshot({type:'jpeg',quality:72,fullPage:false})).toString('base64'); const dimensions=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,clientWidth:document.documentElement.clientWidth,fontSize:parseFloat(getComputedStyle(document.body).fontSize),buttons:[...document.querySelectorAll('a,button')].filter(e=>{const r=e.getBoundingClientRect();return r.width>0&&r.height>0&&r.width<44||r.height>0&&r.height<36}).length})); await page.setViewportSize({width:390,height:844}); await page.reload({waitUntil:'networkidle',timeout:25000}); await page.waitForTimeout(500); shots.mobile=(await page.screenshot({type:'jpeg',quality:72,fullPage:false})).toString('base64'); const mobile=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth+3})); visual={verified:true,dimensions,mobile,notes:[]}; if(mobile.overflow) techIssues.push({category:'Mobile',level:'important',title:'Débordement horizontal mobile',explanation:'La page dépasse la largeur de 390 px lors du rendu.',impact:'Le contenu peut être coupé ou nécessiter un défilement horizontal.',recommendation:'Corriger les largeurs fixes et médias non fluides.',difficulty:'Moyenne',automatable:false}); if(dimensions.fontSize<16) techIssues.push({category:'Design / UX',level:'improvement',title:'Texte principal petit',explanation:`La taille calculée du corps est ${dimensions.fontSize}px.` ,impact:'La lecture peut être inconfortable.','recommendation':'Viser au moins 16 px pour le texte courant.','difficulty':'Facile','automatable':false}); onProgress(75,'Captures desktop et mobile'); } catch(e){ visual={verified:false,error:e.message,notes:['Analyse visuelle non vérifiée : navigateur indisponible ou site bloquant.']}; } finally {if(browser) await browser.close();}
  const issues=[...base.issues,...techIssues]; const checks={'Design / UX':visual.verified,Mobile:true}; const scores=computeScores(issues,checks);
  const counts={critical:issues.filter(i=>i.level==='critical').length,important:issues.filter(i=>i.level==='important').length,improvement:issues.filter(i=>i.level==='improvement').length,passed:base.passed.length};
  onProgress(95,'Construction du rapport');
  return {id:crypto.randomUUID(),url:finalUrl,createdAt:new Date().toISOString(),durationMs:Date.now()-started,status:response.status,headers,meta:base.meta,business:base.business,robots:{verified:robots.verified,present:robots.present,status:robots.status,sitemapReferenced:/sitemap:/i.test(robots.content||'')},sitemap:{verified:sitemap.verified,present:sitemap.present,status:sitemap.status},performance:{responseMs:Date.now()-t,htmlBytes:buf.length},screenshots:shots,visual,issues,passed:base.passed,scores,counts,methodology:{penalties:{critical:28,important:16,improvement:7},rule:'Chaque dimension part de 100. Les pénalités mesurées sont soustraites, avec un minimum de 0. Website Health est la moyenne des dimensions vérifiées.'}};
}
